import { StyleSheet } from "react-native";

import { theme } from "../../theme";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        paddingHorizontal: 10,
        // backgroundColor: 'red',
    },

    null: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    containerList: {
        width: '100%',
        height: 60,
        borderRadius: 10,
        backgroundColor: theme.colors.gray[700],
        marginTop: 12,
        paddingHorizontal: 15,
        justifyContent: 'flex-start',
        alignItems: "center",
        flexDirection: 'row',
        gap: 15,
    },
    btns: {
        position: 'absolute',
        right: 10,
    },
    btnDone: {
        width: 18,
        height: 18,
        backgroundColor: theme.colors.gray[700],
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 6,
        borderColor: 'white',
        borderWidth: 2,
    },

    btnDoneComplete: {
        width: 18,
        height: 18,
        backgroundColor: theme.colors.gray[600],
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        borderColor: theme.colors.gray[600],
        borderWidth: 2,

    },
    btnTrash: {
        width: 25,
        height: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 6,
    },
    containerInput: {
        height: 120,
        backgroundColor: theme.colors.gray[700],
        borderRadius: 10,
        flexDirection: 'row',
        // paddingVertical: 20,
        paddingHorizontal: 10,
        // alignItems: 'center',
        // justifyContent: 'center',

    },
    input: {
        minWidth: 320,
        maxWidth: 320,
        color: theme.colors.white,
        // backgroundColor: theme.colors.gray[800],
        height: 120,
        // borderRadius: 50,
        fontSize: 18,
        // paddingLeft: 20,
        fontFamily: theme.fonts.DidactGothic,
    },
    btnClearAll: {
        width: 60,
        height: 60,
        borderRadius: 50,
        // justifyContent: 'center',
        // alignItems: 'center',
        position: 'absolute',
        top: -85,
        right: 25,
    },
    btnAdd: {
        position: 'absolute',
        width: 60,
        height: 60,
        borderRadius: 50,
        backgroundColor: theme.colors.green,
        justifyContent: 'center',
        alignItems: 'center',
        right: 20,
        bottom: 20,
    },
    inserir: {
        // width: 60,
        // height: 60,
        // borderRadius: 50,
        // justifyContent: 'center',
        // alignItems: 'center',
        position: 'absolute',
        color: theme.colors.white,
        fontFamily: theme.fonts.DidactGothic,
        fontWeight: 'bold',
        fontSize: 16,
        paddingLeft: 10,
        right: 10,
        bottom: 10,
    },
});

